import type { AgentDetail, AgentSummary, RuntimeLog } from '../../src/api/types';
import type { StoreData } from '../../src/store/store-context';

export const mockStoreData: StoreData = {
  agents: [
    {
      id: 'ac-agent-001',
      instanceId: 'ins-life-001',
      name: '寿险业务助手',
      type: 'official',
      engine: 'AstronClaw Runtime',
      status: 'running',
      version: 'v1.8.0',
      department: '寿险事业部',
      owner: '平台管理员',
      containers: 3,
      skills: 2,
      skillList: ['合同条款抽取', '客户意图识别'],
      userUsed: 38,
      userMax: 200,
      qps: 12,
      model: 'Spark Max',
      fallbackModel: 'Spark Pro',
      cpu: 4,
      memory: 8,
      storage: 60,
      gpu: '0',
      concurrency: 50,
      dailyLimit: 100000,
      timeout: 300000,
      description: '面向寿险业务人员的官方智能体实例。',
      createdAt: '2026-07-01 09:00:00',
      logs: [{ id: 'log-1', ts: '2026-07-06 09:30:00', level: 'success', message: '模型调用正常' }],
    },
    {
      id: 'ac-agent-002',
      instanceId: 'ins-ops-001',
      name: '运维巡检助手',
      type: 'official',
      engine: 'AstronClaw Runtime',
      status: 'abnormal',
      version: 'v1.6.2',
      department: '运维中心',
      owner: '运维值班员',
      containers: 2,
      skills: 1,
      skillList: ['异常根因分析'],
      userUsed: 12,
      userMax: 80,
      qps: 5,
      model: 'Spark Max',
      fallbackModel: 'Spark Lite',
      cpu: 2,
      memory: 4,
      storage: 40,
      gpu: '0',
      concurrency: 20,
      dailyLimit: 40000,
      timeout: 300000,
      description: '用于巡检告警归因与自动化处置。',
      createdAt: '2026-07-02 10:00:00',
      logs: [{ id: 'log-2', ts: '2026-07-06 10:30:00', level: 'warn', message: 'QPS 触发预警阈值' }],
    },
  ],
  departments: [
    { id: 'dep-root', name: '讯飞总部', parentId: null, manager: '平台管理员' },
    { id: 'dep-life', name: '寿险事业部', parentId: 'dep-root', manager: '李明' },
    { id: 'dep-ops', name: '运维中心', parentId: 'dep-root', manager: '王蕾' },
  ],
  members: [
    {
      id: 'u-admin',
      name: '平台管理员',
      empNo: 'A0001',
      deptId: 'dep-root',
      roleId: 'role-admin',
      email: 'admin@example.com',
      status: 'active',
      seat: 'assigned',
      lastLogin: '2026-07-06 09:00:00',
      sso: true,
    },
    {
      id: 'u-ops',
      name: '运维值班员',
      empNo: 'O0001',
      deptId: 'dep-ops',
      roleId: 'role-ops',
      email: 'ops@example.com',
      status: 'active',
      seat: 'assigned',
      lastLogin: '2026-07-06 08:30:00',
      sso: true,
    },
  ],
  roles: [
    {
      id: 'role-admin',
      name: '平台管理员',
      desc: '拥有全部管理权限',
      dataScope: '全域',
      instanceScope: '全部实例',
      permissions: ['agent.create', 'agent.lifecycle', 'model.manage', 'security.manage'],
      memberCount: 0,
      builtIn: true,
    },
    {
      id: 'role-ops',
      name: '运维管理员',
      desc: '负责运维巡检和告警处理',
      dataScope: '运维中心',
      instanceScope: '部门实例',
      permissions: ['agent.lifecycle', 'ops.manage'],
      memberCount: 0,
      builtIn: false,
    },
  ],
  opLogs: [
    {
      id: 'op-1',
      ts: '2026-07-06 09:30:00',
      operator: '平台管理员',
      module: '智能体',
      action: '同步状态',
      target: '寿险业务助手',
      result: 'success',
      ip: '127.0.0.1',
      detail: 'e2e mock 操作日志',
    },
  ],
  models: [
    {
      id: 'model-spark-max',
      name: 'Spark Max',
      provider: '讯飞星火',
      model: 'spark-max',
      apiEndpoint: 'https://api.xunfei.cn/v1/chat',
      description: '通用大模型主路由',
      status: 'available',
      price: 28,
      todayCalls: 1200,
      todayTokens: 88,
      errorRate: 0.2,
      avgLatency: 860,
      containerCost: 130,
    },
    {
      id: 'model-spark-pro',
      name: 'Spark Pro',
      provider: '讯飞星火',
      model: 'spark-pro',
      apiEndpoint: 'https://api.xunfei.cn/v1/chat',
      description: '备用模型',
      status: 'available',
      price: 15,
      todayCalls: 420,
      todayTokens: 36,
      errorRate: 0.1,
      avgLatency: 720,
      containerCost: 90,
    },
  ],
  alerts: [
    {
      id: 'alert-1',
      level: 'critical',
      source: '运维巡检助手',
      errorCode: 'AGENT_QPS_HIGH',
      category: '运行时',
      type: 'QPS 异常',
      triggeredAt: '2026-07-06 10:12:00',
      owner: '运维值班员',
      status: 'pending',
      impact: '响应延迟升高',
      detail: 'QPS 连续 5 分钟超过阈值',
      rootCause: '流量突增',
      suggestion: '扩容容器并检查限流策略',
    },
    {
      id: 'alert-2',
      level: 'warning',
      source: '模型网关',
      errorCode: 'MODEL_LATENCY',
      category: '模型',
      type: '延迟预警',
      triggeredAt: '2026-07-06 11:00:00',
      owner: '平台管理员',
      status: 'processing',
      impact: '部分请求延迟',
      detail: '备用模型平均延迟偏高',
      suggestion: '切换备用模型策略',
    },
  ],
  skills: [
    {
      id: 'skill-1',
      name: '合同条款抽取',
      packageName: 'contract-extractor',
      source: '官方',
      version: '1.2.0',
      status: 'enabled',
      boundAgents: 0,
      creator: '平台管理员',
      updatedAt: '2026-07-05',
      category: '文本理解',
      allowedRoles: ['role-admin'],
    },
    {
      id: 'skill-2',
      name: '异常根因分析',
      packageName: 'ops-rca',
      source: '官方',
      version: '1.0.3',
      status: 'reviewing',
      boundAgents: 0,
      creator: '运维值班员',
      updatedAt: '2026-07-04',
      category: '运维',
      allowedRoles: ['role-admin', 'role-ops'],
    },
  ],
  knowledge: [
    { id: 'mem-1', title: '合同评审要点清单', level: '部门级', owner: '李明', tags: ['合同', '法务'], refs: 18, updatedAt: '2026-07-05', shareStatus: 'shared' },
    { id: 'mem-2', title: '运维告警处置流程', level: '全局', owner: '王蕾', tags: ['运维', '告警'], refs: 9, updatedAt: '2026-07-04', shareStatus: 'pending' },
  ],
  knowledgeFiles: [
    {
      id: 'kb-file-1',
      name: '寿险产品手册.pdf',
      type: 'pdf',
      size: 2048,
      category: '产品资料',
      uploadedBy: '李明',
      uploadedAt: '2026-07-03',
      status: 'indexed',
      chunks: 126,
      refs: 32,
    },
    {
      id: 'kb-file-2',
      name: '告警处置 SOP.md',
      type: 'md',
      size: 256,
      category: '运维资料',
      uploadedBy: '王蕾',
      uploadedAt: '2026-07-04',
      status: 'processing',
      chunks: 18,
      refs: 4,
    },
  ],
  seats: [{ id: 'seat-1', pkg: '企业标准包', total: 500, used: 238, dept: '寿险事业部', expireAt: '2027-07-01' }],
  securityPolicies: [
    { id: 'policy-1', name: '敏感信息脱敏', desc: '对模型请求中的证件号和手机号脱敏', enabled: true },
    { id: 'policy-2', name: '高危操作二次确认', desc: '删除、停用、授权回收需要二次确认', enabled: true },
  ],
  channels: [
    { id: 'channel-1', name: '企业微信服务号', type: '企业微信', status: 'connected', boundAgent: 'ac-agent-001', messages: 1280, updatedAt: '2026-07-06 09:00:00' },
    { id: 'channel-2', name: '内部工单机器人', type: 'Webhook', status: 'error', boundAgent: 'ac-agent-002', messages: 302, updatedAt: '2026-07-06 10:00:00' },
  ],
  inspection: {
    id: 'inspection-1',
    ts: '2026-07-06 10:30:00',
    scope: '全域 · 2 个实例',
    total: 3,
    pass: 1,
    warn: 1,
    fail: 1,
    items: [
      { id: 'insp-1', category: '模型', name: '主模型可用性', result: 'pass', detail: '主模型调用正常', suggestion: '继续监控' },
      { id: 'insp-2', category: '运行时', name: '容器资源水位', result: 'warn', detail: '部分容器 CPU 超过 75%', suggestion: '建议扩容' },
      { id: 'insp-3', category: '安全', name: '高危权限校验', result: 'fail', detail: '发现未闭环授权', suggestion: '立即复核角色权限' },
    ],
  },
};

export const mockAgentSummaries: AgentSummary[] = [
  {
    id: 'ac-agent-001',
    botId: 'bot-life',
    instanceId: 'ins-life-001',
    name: '寿险业务助手',
    type: 'astronclaw',
    status: 'running',
    version: 'v1.8.0',
    department: { id: 'dep-life', name: '寿险事业部' },
    owner: { id: 'u-admin', name: '平台管理员' },
    containerCount: 3,
    skillCount: 2,
    knowledgeBaseCount: 1,
    primaryModel: { id: 'model-spark-max', name: 'Spark Max' },
    backupModel: { id: 'model-spark-pro', name: 'Spark Pro' },
    cpu: 4,
    memory: '8Gi',
    storage: '60Gi',
    gpu: 0,
    concurrencyLimit: 50,
    dailyCallLimit: 100000,
    timeoutMs: 300000,
    currentUsers: 38,
    maxUsers: 200,
    qps: 12,
    createdAt: '2026-07-01T09:00:00+08:00',
    updatedAt: '2026-07-06T09:30:00+08:00',
    description: '面向寿险业务人员的官方智能体实例。',
    skillNames: ['合同条款抽取', '客户意图识别'],
  },
  {
    id: 'ac-agent-002',
    botId: 'bot-ops',
    instanceId: 'ins-ops-001',
    name: '运维巡检助手',
    type: 'astronclaw',
    status: 'abnormal',
    version: 'v1.6.2',
    department: { id: 'dep-ops', name: '运维中心' },
    owner: { id: 'u-ops', name: '运维值班员' },
    containerCount: 2,
    skillCount: 1,
    knowledgeBaseCount: 1,
    primaryModel: { id: 'model-spark-max', name: 'Spark Max' },
    backupModel: { id: 'model-spark-pro', name: 'Spark Pro' },
    cpu: 2,
    memory: '4Gi',
    storage: '40Gi',
    gpu: 0,
    concurrencyLimit: 20,
    dailyCallLimit: 40000,
    timeoutMs: 300000,
    currentUsers: 12,
    maxUsers: 80,
    qps: 5,
    createdAt: '2026-07-02T10:00:00+08:00',
    updatedAt: '2026-07-06T10:30:00+08:00',
    description: '用于巡检告警归因与自动化处置。',
    skillNames: ['异常根因分析'],
  },
];

export const mockRuntimeLogs: RuntimeLog[] = [
  { id: 'runtime-1', ts: '2026-07-06 09:30:00', level: 'success', message: '模型调用正常' },
  { id: 'runtime-2', ts: '2026-07-06 09:31:00', level: 'info', message: '完成一轮知识库检索' },
];

export const mockAgentDetail: AgentDetail = {
  basic: mockAgentSummaries[0],
  runtime: { logs: mockRuntimeLogs, cpuUsage: 42, memoryUsage: 58, storageUsage: 33 },
  skills: [
    { id: 'skill-1', name: '合同条款抽取', version: '1.2.0', status: 'enabled', category: '文本理解' },
    { id: 'skill-3', name: '客户意图识别', version: '1.1.0', status: 'enabled', category: '对话理解' },
  ],
  knowledgeBases: [{ id: 'kb-1', name: '寿险产品知识库', fileCount: 12, status: 'ready' }],
  deployHistory: [{ id: 'deploy-1', version: 'v1.8.0', action: 'deploy', status: 'success', operator: '平台管理员', createdAt: '2026-07-05T16:00:00+08:00' }],
  versionHistory: [{ id: 'version-1', version: 'v1.8.0', action: 'upgrade', status: 'success', operator: '平台管理员', createdAt: '2026-07-05T15:30:00+08:00' }],
  callStats: { todayCalls: 1280, todayTokens: 92000, successRate: 99.7, avgLatencyMs: 860, peakQps: 18 },
  alerts: [{ id: 'alert-life-1', level: 'warning', type: '延迟预警', message: '最近 5 分钟平均延迟偏高', status: 'processing', triggeredAt: '2026-07-06 09:20:00' }],
  auditLogs: [{ id: 'audit-1', ts: '2026-07-06 09:30:00', operator: '平台管理员', action: '同步状态', result: 'success', detail: 'e2e mock 审计记录' }],
};

export const mockSharedAgent = {
  agent: {
    id: 'ac-agent-001',
    name: '寿险业务助手',
    status: 'running',
    engine: 'AstronClaw Runtime',
    version: 'v1.8.0',
    description: '面向寿险业务人员的官方智能体实例。',
    department: '寿险事业部',
    owner: '平台管理员',
    primaryModel: 'Spark Max',
    backupModel: 'Spark Pro',
    createdAt: '2026-07-01 09:00:00',
    skillNames: ['合同条款抽取', '客户意图识别'],
  },
  expiresAt: '2026-12-31 23:59:59',
};
