// 由 D:\文件\FRONTEND_API.md 生成，用于 Playwright 接口契约测试。
// 生成时间：2026-07-06 13:47:37
// 接口总数：232

export interface ApiContractCase {
  method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';
  path: string;
  summary: string;
  pathParams: string[];
  query: string[];
  body: string | null;
  permission: string;
  mutating: boolean;
  devOnly: boolean;
  download: boolean;
}

export interface ApiContractGroup {
  name: string;
  cases: ApiContractCase[];
}

export const apiContractGroups = [
  {
    name: '健康检查',
    cases: [
      {
        method: 'GET',
        path: '/health',
        summary: 'Health',
        pathParams: [],
        query: [],
        body: null,
        permission: '公开',
        mutating: false,
        devOnly: false,
        download: false,
      },
    ],
  },
  {
    name: '开发/测试辅助',
    cases: [
      {
        method: 'POST',
        path: '/dev/agent-logs',
        summary: 'Dev Agent Log',
        pathParams: [],
        query: [],
        body: 'object',
        permission: '开发/测试辅助，生产不要给前端调用',
        mutating: true,
        devOnly: true,
        download: false,
      },
      {
        method: 'POST',
        path: '/dev/cost/archive',
        summary: 'Dev Archive Cost',
        pathParams: [],
        query: [],
        body: 'object',
        permission: '开发/测试辅助，生产不要给前端调用',
        mutating: true,
        devOnly: true,
        download: false,
      },
      {
        method: 'POST',
        path: '/dev/model-call-logs',
        summary: 'Dev Model Call Log',
        pathParams: [],
        query: [],
        body: 'object',
        permission: '开发/测试辅助，生产不要给前端调用',
        mutating: true,
        devOnly: true,
        download: false,
      },
      {
        method: 'POST',
        path: '/dev/model-gateway/call',
        summary: 'Dev Model Gateway Call',
        pathParams: [],
        query: [],
        body: 'object',
        permission: '开发/测试辅助，生产不要给前端调用',
        mutating: true,
        devOnly: true,
        download: false,
      },
      {
        method: 'POST',
        path: '/dev/seed',
        summary: 'Dev Seed',
        pathParams: [],
        query: [],
        body: null,
        permission: '开发/测试辅助，生产不要给前端调用',
        mutating: true,
        devOnly: true,
        download: false,
      },
    ],
  },
  {
    name: '认证与当前用户',
    cases: [
      {
        method: 'POST',
        path: '/auth/login',
        summary: 'Login',
        pathParams: [],
        query: [],
        body: 'LoginRequest',
        permission: '公开',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/auth/logout',
        summary: 'Logout',
        pathParams: [],
        query: [],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/auth/refresh',
        summary: 'Refresh Token',
        pathParams: [],
        query: [],
        body: 'object',
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/auth/sso/callback',
        summary: 'Sso Callback',
        pathParams: [],
        query: ['provider', 'subject', 'username'],
        body: null,
        permission: '公开',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/auth/sso/login',
        summary: 'Sso Login',
        pathParams: [],
        query: 'provider',
        body: null,
        permission: '公开',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/auth/sso/logout',
        summary: 'Sso Logout',
        pathParams: [],
        query: [],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/me',
        summary: 'Me',
        pathParams: [],
        query: [],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/me/permissions',
        summary: 'Me Permissions',
        pathParams: [],
        query: [],
        body: null,
        permission: 'security:manage',
        mutating: false,
        devOnly: false,
        download: false,
      },
    ],
  },
  {
    name: 'SSO 配置',
    cases: [
      {
        method: 'GET',
        path: '/sso/providers',
        summary: 'List Sso Providers',
        pathParams: [],
        query: [],
        body: null,
        permission: 'security:manage',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/sso/providers',
        summary: 'Create Sso Provider',
        pathParams: [],
        query: [],
        body: 'object',
        permission: 'security:manage',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'PUT',
        path: '/sso/providers/{provider_id}',
        summary: 'Update Sso Provider',
        pathParams: ['provider_id'],
        query: [],
        body: 'object',
        permission: 'security:manage',
        mutating: true,
        devOnly: false,
        download: false,
      },
    ],
  },
  {
    name: '智能体管理',
    cases: [
      {
        method: 'GET',
        path: '/agents',
        summary: 'List Agents',
        pathParams: [],
        query: ['keyword', 'status', 'departmentId', 'ownerId', 'modelId', 'page', 'pageSize'],
        body: null,
        permission: 'agent:view/create/deploy/delete/ops/batch/share 按动作区分',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/agents',
        summary: 'Create Agent',
        pathParams: [],
        query: [],
        body: 'AgentCreateRequest',
        permission: 'agent:view/create/deploy/delete/ops/batch/share 按动作区分',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/agents/{agent_id}',
        summary: 'Get Agent',
        pathParams: ['agent_id'],
        query: [],
        body: null,
        permission: 'agent:view/create/deploy/delete/ops/batch/share 按动作区分',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'DELETE',
        path: '/agents/{agent_id}',
        summary: 'Delete Agent',
        pathParams: ['agent_id'],
        query: [],
        body: null,
        permission: 'agent:view/create/deploy/delete/ops/batch/share 按动作区分',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/agents/{agent_id}/archive',
        summary: 'Lifecycle',
        pathParams: ['agent_id'],
        query: [],
        body: 'object',
        permission: 'agent:view/create/deploy/delete/ops/batch/share 按动作区分',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/agents/{agent_id}/deploy',
        summary: 'Lifecycle',
        pathParams: ['agent_id'],
        query: [],
        body: 'object',
        permission: 'agent:view/create/deploy/delete/ops/batch/share 按动作区分',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/agents/{agent_id}/logs',
        summary: 'Agent Logs',
        pathParams: ['agent_id'],
        query: ['logType', 'level', 'keyword', 'startTime', 'endTime', 'page', 'pageSize'],
        body: null,
        permission: 'agent:view/create/deploy/delete/ops/batch/share 按动作区分',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'PUT',
        path: '/agents/{agent_id}/model',
        summary: 'Switch Model',
        pathParams: ['agent_id'],
        query: [],
        body: 'object',
        permission: 'agent:view/create/deploy/delete/ops/batch/share 按动作区分',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/agents/{agent_id}/restart',
        summary: 'Lifecycle',
        pathParams: ['agent_id'],
        query: [],
        body: 'object',
        permission: 'agent:view/create/deploy/delete/ops/batch/share 按动作区分',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/agents/{agent_id}/rollback',
        summary: 'Rollback Agent',
        pathParams: ['agent_id'],
        query: [],
        body: 'object',
        permission: 'agent:view/create/deploy/delete/ops/batch/share 按动作区分',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/agents/{agent_id}/runtime-config',
        summary: 'Get Runtime Config',
        pathParams: ['agent_id'],
        query: ['page', 'pageSize'],
        body: null,
        permission: 'agent:view/create/deploy/delete/ops/batch/share 按动作区分',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'PUT',
        path: '/agents/{agent_id}/runtime-config',
        summary: 'Runtime Config',
        pathParams: ['agent_id'],
        query: [],
        body: 'object',
        permission: 'agent:view/create/deploy/delete/ops/batch/share 按动作区分',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/agents/{agent_id}/start',
        summary: 'Lifecycle',
        pathParams: ['agent_id'],
        query: [],
        body: 'object',
        permission: 'agent:view/create/deploy/delete/ops/batch/share 按动作区分',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/agents/{agent_id}/state-events',
        summary: 'Agent State Events',
        pathParams: ['agent_id'],
        query: ['page', 'pageSize'],
        body: null,
        permission: 'agent:view/create/deploy/delete/ops/batch/share 按动作区分',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/agents/{agent_id}/stop',
        summary: 'Lifecycle',
        pathParams: ['agent_id'],
        query: [],
        body: 'object',
        permission: 'agent:view/create/deploy/delete/ops/batch/share 按动作区分',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/agents/{agent_id}/sync',
        summary: 'Sync Agent',
        pathParams: ['agent_id'],
        query: [],
        body: null,
        permission: 'agent:view/create/deploy/delete/ops/batch/share 按动作区分',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/agents/{agent_id}/upgrade',
        summary: 'Lifecycle',
        pathParams: ['agent_id'],
        query: [],
        body: 'object',
        permission: 'agent:view/create/deploy/delete/ops/batch/share 按动作区分',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/agents/{agent_id}/versions',
        summary: 'Agent Versions',
        pathParams: ['agent_id'],
        query: ['page', 'pageSize'],
        body: null,
        permission: 'agent:view/create/deploy/delete/ops/batch/share 按动作区分',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/agents/{agent_id}/violation-offline',
        summary: 'Lifecycle',
        pathParams: ['agent_id'],
        query: [],
        body: 'object',
        permission: 'agent:view/create/deploy/delete/ops/batch/share 按动作区分',
        mutating: true,
        devOnly: false,
        download: false,
      },
    ],
  },
  {
    name: '智能体任务与同步',
    cases: [
      {
        method: 'GET',
        path: '/agent-tasks/{task_id}',
        summary: 'Get Task',
        pathParams: ['task_id'],
        query: [],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/sync-jobs',
        summary: 'Runtime Sync Jobs',
        pathParams: [],
        query: ['page', 'pageSize', 'status'],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/sync-jobs',
        summary: 'Create Runtime Sync Job',
        pathParams: [],
        query: [],
        body: 'object',
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/sync-jobs/{job_id}',
        summary: 'Runtime Sync Job Detail',
        pathParams: ['job_id'],
        query: [],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: false,
        devOnly: false,
        download: false,
      },
    ],
  },
  {
    name: '批量任务',
    cases: [
      {
        method: 'POST',
        path: '/batch-tasks',
        summary: 'Create Batch',
        pathParams: [],
        query: [],
        body: 'object',
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/batch-tasks/{batch_id}',
        summary: 'Get Batch',
        pathParams: ['batch_id'],
        query: [],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/batch-tasks/{batch_id}/export',
        summary: 'Export Batch',
        pathParams: ['batch_id'],
        query: [],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: false,
        devOnly: false,
        download: true,
      },
      {
        method: 'GET',
        path: '/batch-tasks/{batch_id}/items',
        summary: 'Get Batch Items',
        pathParams: ['batch_id'],
        query: ['page', 'pageSize'],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: false,
        devOnly: false,
        download: false,
      },
    ],
  },
  {
    name: '组织、角色与权限',
    cases: [
      {
        method: 'GET',
        path: '/org/departments/tree',
        summary: 'Departments Tree',
        pathParams: [],
        query: [],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/org/positions',
        summary: 'Positions',
        pathParams: [],
        query: ['departmentId', 'status', 'page', 'pageSize'],
        body: null,
        permission: 'security:manage',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/org/positions',
        summary: 'Create Position',
        pathParams: [],
        query: [],
        body: 'object',
        permission: 'security:manage',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'PUT',
        path: '/org/positions/{position_id}',
        summary: 'Update Position',
        pathParams: ['position_id'],
        query: [],
        body: 'object',
        permission: 'security:manage',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/org/sync-jobs',
        summary: 'Org Sync Jobs',
        pathParams: [],
        query: ['page', 'pageSize', 'status', 'source'],
        body: null,
        permission: 'security:manage',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/org/sync-jobs',
        summary: 'Create Org Sync Job',
        pathParams: [],
        query: [],
        body: 'object',
        permission: 'security:manage',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/org/sync-jobs/{job_id}',
        summary: 'Org Sync Job Detail',
        pathParams: ['job_id'],
        query: [],
        body: null,
        permission: 'security:manage',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/org/users',
        summary: 'Users',
        pathParams: [],
        query: ['page', 'pageSize', 'keyword', 'departmentId', 'status', 'seatStatus'],
        body: null,
        permission: 'security:manage',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/org/users/{user_id}/password-reset',
        summary: 'Reset User Password',
        pathParams: ['user_id'],
        query: [],
        body: 'object',
        permission: 'security:manage',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'PUT',
        path: '/org/users/{user_id}/status',
        summary: 'Update User Status',
        pathParams: ['user_id'],
        query: [],
        body: 'object',
        permission: 'security:manage',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/permission-matrix',
        summary: 'Permission Matrix',
        pathParams: [],
        query: [],
        body: null,
        permission: 'security:manage',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/permissions',
        summary: 'Permissions',
        pathParams: [],
        query: [],
        body: null,
        permission: 'security:manage',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/roles',
        summary: 'Roles',
        pathParams: [],
        query: ['page', 'pageSize', 'keyword', 'status'],
        body: null,
        permission: 'security:manage',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/roles',
        summary: 'Create Role',
        pathParams: [],
        query: [],
        body: 'object',
        permission: 'security:manage',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'PUT',
        path: '/roles/{role_id}',
        summary: 'Update Role',
        pathParams: ['role_id'],
        query: [],
        body: 'object',
        permission: 'security:manage',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'DELETE',
        path: '/roles/{role_id}',
        summary: 'Delete Role',
        pathParams: ['role_id'],
        query: [],
        body: null,
        permission: 'security:manage',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'PUT',
        path: '/roles/{role_id}/permissions',
        summary: 'Update Role Permissions',
        pathParams: ['role_id'],
        query: [],
        body: 'object',
        permission: 'security:manage',
        mutating: true,
        devOnly: false,
        download: false,
      },
    ],
  },
  {
    name: '模型网关与模型管理',
    cases: [
      {
        method: 'GET',
        path: '/audit/model-call-logs',
        summary: 'Model Logs',
        pathParams: [],
        query: ['page', 'pageSize', 'modelId', 'agentId', 'userId', 'departmentId', 'status', 'startTime', 'endTime'],
        body: null,
        permission: 'audit:view / audit:export 按接口区分',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/audit/model-call-logs/export',
        summary: 'Model Call Logs Export',
        pathParams: [],
        query: 'approvalId',
        body: null,
        permission: 'audit:view / audit:export 按接口区分',
        mutating: false,
        devOnly: false,
        download: true,
      },
      {
        method: 'GET',
        path: '/model-call-logs',
        summary: 'Model Logs',
        pathParams: [],
        query: ['page', 'pageSize', 'modelId', 'agentId', 'userId', 'departmentId', 'status', 'startTime', 'endTime'],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/model-policy-hits',
        summary: 'Policy Hits',
        pathParams: [],
        query: ['startTime', 'endTime', 'modelId'],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/model-quotas',
        summary: 'Model Quotas',
        pathParams: [],
        query: [],
        body: null,
        permission: 'model:manage',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/model-quotas',
        summary: 'Create Model Quota',
        pathParams: [],
        query: [],
        body: 'object',
        permission: 'model:manage',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'PUT',
        path: '/model-quotas/{quota_id}',
        summary: 'Update Model Quota',
        pathParams: ['quota_id'],
        query: [],
        body: 'object',
        permission: 'model:manage',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'DELETE',
        path: '/model-quotas/{quota_id}',
        summary: 'Delete Model Quota',
        pathParams: ['quota_id'],
        query: [],
        body: null,
        permission: 'model:manage',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/model-route-policies',
        summary: 'Route Policies',
        pathParams: [],
        query: [],
        body: null,
        permission: 'model:manage',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/model-route-policies',
        summary: 'Create Route Policy',
        pathParams: [],
        query: [],
        body: 'object',
        permission: 'model:manage',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'PUT',
        path: '/model-route-policies/{policy_id}',
        summary: 'Update Route Policy',
        pathParams: ['policy_id'],
        query: [],
        body: 'object',
        permission: 'model:manage',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'DELETE',
        path: '/model-route-policies/{policy_id}',
        summary: 'Delete Route Policy',
        pathParams: ['policy_id'],
        query: [],
        body: null,
        permission: 'model:manage',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/models',
        summary: 'Models',
        pathParams: [],
        query: ['page', 'pageSize', 'keyword', 'status', 'provider', 'type'],
        body: null,
        permission: 'model:manage 写操作；列表登录可读',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/models',
        summary: 'Create Model',
        pathParams: [],
        query: [],
        body: 'object',
        permission: 'model:manage 写操作；列表登录可读',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/models/{model_id}',
        summary: 'Model Detail',
        pathParams: ['model_id'],
        query: [],
        body: null,
        permission: 'model:manage / model:secret_view 按动作区分',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'PUT',
        path: '/models/{model_id}',
        summary: 'Update Model',
        pathParams: ['model_id'],
        query: [],
        body: 'object',
        permission: 'model:manage / model:secret_view 按动作区分',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/models/{model_id}/disable',
        summary: 'Model Action',
        pathParams: ['model_id'],
        query: [],
        body: 'object',
        permission: 'model:manage / model:secret_view 按动作区分',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/models/{model_id}/enable',
        summary: 'Model Action',
        pathParams: ['model_id'],
        query: [],
        body: 'object',
        permission: 'model:manage / model:secret_view 按动作区分',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/models/{model_id}/probe',
        summary: 'Model Action',
        pathParams: ['model_id'],
        query: [],
        body: 'object',
        permission: 'model:manage / model:secret_view 按动作区分',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/models/{model_id}/secret',
        summary: 'Model Secret View',
        pathParams: ['model_id'],
        query: [],
        body: null,
        permission: 'model:manage / model:secret_view 按动作区分',
        mutating: false,
        devOnly: false,
        download: false,
      },
    ],
  },
  {
    name: 'Skill 管理',
    cases: [
      {
        method: 'POST',
        path: '/agents/{agent_id}/skills/{skill_id}/install',
        summary: 'Bind Skill',
        pathParams: ['agent_id', 'skill_id'],
        query: [],
        body: null,
        permission: 'skill:manage 写操作；列表登录可读',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/agents/{agent_id}/skills/{skill_id}/uninstall',
        summary: 'Bind Skill',
        pathParams: ['agent_id', 'skill_id'],
        query: [],
        body: null,
        permission: 'skill:manage 写操作；列表登录可读',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/skills',
        summary: 'Skills',
        pathParams: [],
        query: ['keyword', 'status', 'source', 'category', 'page', 'pageSize'],
        body: null,
        permission: 'skill:manage 写操作；列表登录可读',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/skills',
        summary: 'Create Skill',
        pathParams: [],
        query: [],
        body: 'object',
        permission: 'skill:manage 写操作；列表登录可读',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/skills/import',
        summary: 'Create Skill',
        pathParams: [],
        query: [],
        body: 'object',
        permission: 'skill:manage 写操作；列表登录可读',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/skills/{skill_id}',
        summary: 'Skill Detail',
        pathParams: ['skill_id'],
        query: [],
        body: null,
        permission: 'skill:manage 写操作；列表登录可读',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'PUT',
        path: '/skills/{skill_id}',
        summary: 'Update Skill',
        pathParams: ['skill_id'],
        query: [],
        body: 'object',
        permission: 'skill:manage 写操作；列表登录可读',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/skills/{skill_id}/grants',
        summary: 'Skill Grants',
        pathParams: ['skill_id'],
        query: [],
        body: null,
        permission: 'skill:manage 写操作；列表登录可读',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/skills/{skill_id}/grants',
        summary: 'Create Skill Grant',
        pathParams: ['skill_id'],
        query: [],
        body: 'object',
        permission: 'skill:manage 写操作；列表登录可读',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/skills/{skill_id}/review',
        summary: 'Review Skill',
        pathParams: ['skill_id'],
        query: [],
        body: 'object',
        permission: 'skill:manage 写操作；列表登录可读',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/skills/{skill_id}/reviews',
        summary: 'Skill Reviews',
        pathParams: ['skill_id'],
        query: [],
        body: null,
        permission: 'skill:manage 写操作；列表登录可读',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/skills/{skill_id}/versions',
        summary: 'Skill Versions',
        pathParams: ['skill_id'],
        query: [],
        body: null,
        permission: 'skill:manage 写操作；列表登录可读',
        mutating: false,
        devOnly: false,
        download: false,
      },
    ],
  },
  {
    name: '知识库',
    cases: [
      {
        method: 'POST',
        path: '/agents/{agent_id}/knowledge-bases/{kb_id}/bind',
        summary: 'Bind Kb',
        pathParams: ['agent_id', 'kb_id'],
        query: [],
        body: null,
        permission: 'agent:view/create/deploy/delete/ops/batch/share 按动作区分',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'DELETE',
        path: '/agents/{agent_id}/knowledge-bases/{kb_id}/bind',
        summary: 'Unbind Kb',
        pathParams: ['agent_id', 'kb_id'],
        query: [],
        body: null,
        permission: 'agent:view/create/deploy/delete/ops/batch/share 按动作区分',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/knowledge-bases',
        summary: 'Knowledge Bases',
        pathParams: [],
        query: [],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/knowledge-bases',
        summary: 'Create Kb',
        pathParams: [],
        query: [],
        body: 'object',
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/knowledge-bases/{kb_id}/files',
        summary: 'Kb Files',
        pathParams: ['kb_id'],
        query: [],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/knowledge-bases/{kb_id}/files',
        summary: 'Create Kb File',
        pathParams: ['kb_id'],
        query: [],
        body: 'object',
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/knowledge-bases/{kb_id}/grants',
        summary: 'Knowledge Grants',
        pathParams: ['kb_id'],
        query: [],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/knowledge-bases/{kb_id}/grants',
        summary: 'Create Knowledge Grant',
        pathParams: ['kb_id'],
        query: [],
        body: 'object',
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'DELETE',
        path: '/knowledge-files/{file_id}',
        summary: 'Delete Knowledge File',
        pathParams: ['file_id'],
        query: [],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/knowledge-files/{file_id}/reindex',
        summary: 'Reindex Knowledge File',
        pathParams: ['file_id'],
        query: [],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: true,
        devOnly: false,
        download: false,
      },
    ],
  },
  {
    name: '监控、告警与通知',
    cases: [
      {
        method: 'GET',
        path: '/alert-rules',
        summary: 'List Alert Rules',
        pathParams: [],
        query: ['status', 'metricName', 'page', 'pageSize'],
        body: null,
        permission: 'alert:manage 写操作',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/alert-rules',
        summary: 'Create Alert Rule',
        pathParams: [],
        query: [],
        body: 'object',
        permission: 'alert:manage 写操作',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'PUT',
        path: '/alert-rules/{rule_id}',
        summary: 'Update Alert Rule',
        pathParams: ['rule_id'],
        query: [],
        body: 'object',
        permission: 'alert:manage 写操作',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/alerts',
        summary: 'Alerts',
        pathParams: [],
        query: ['page', 'pageSize', 'level', 'status', 'sourceType'],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/alerts',
        summary: 'Create Alert',
        pathParams: [],
        query: [],
        body: 'object',
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/alerts/{alert_id}',
        summary: 'Alert Detail',
        pathParams: ['alert_id'],
        query: [],
        body: null,
        permission: 'alert:manage 写操作；列表登录可读',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/alerts/{alert_id}/claim',
        summary: 'Alert Action',
        pathParams: ['alert_id'],
        query: [],
        body: 'object',
        permission: 'alert:manage 写操作；列表登录可读',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/alerts/{alert_id}/close',
        summary: 'Alert Action',
        pathParams: ['alert_id'],
        query: [],
        body: 'object',
        permission: 'alert:manage 写操作；列表登录可读',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/alerts/{alert_id}/events',
        summary: 'Alert Events',
        pathParams: ['alert_id'],
        query: [],
        body: null,
        permission: 'alert:manage 写操作；列表登录可读',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/alerts/{alert_id}/process',
        summary: 'Alert Action',
        pathParams: ['alert_id'],
        query: [],
        body: 'object',
        permission: 'alert:manage 写操作；列表登录可读',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/alerts/{alert_id}/suspend',
        summary: 'Alert Action',
        pathParams: ['alert_id'],
        query: [],
        body: 'object',
        permission: 'alert:manage 写操作；列表登录可读',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/alerts/{alert_id}/transfer',
        summary: 'Alert Action',
        pathParams: ['alert_id'],
        query: [],
        body: 'object',
        permission: 'alert:manage 写操作；列表登录可读',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/monitor/metrics',
        summary: 'List Metrics',
        pathParams: [],
        query: ['sourceType', 'sourceId', 'metricName', 'page', 'pageSize'],
        body: null,
        permission: 'alert:manage 写操作；读取登录可读',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/monitor/metrics',
        summary: 'Collect Metrics',
        pathParams: [],
        query: [],
        body: 'object',
        permission: 'alert:manage 写操作；读取登录可读',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/monitor/overview',
        summary: 'Monitor Overview',
        pathParams: [],
        query: [],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/notifications',
        summary: 'Notifications',
        pathParams: [],
        query: ['page', 'pageSize', 'status', 'type'],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/notifications/scan-seat-expirations',
        summary: 'Scan Seat Expirations',
        pathParams: [],
        query: [],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/notifications/summary',
        summary: 'Notification Summary',
        pathParams: [],
        query: [],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/notifications/{notification_id}/read',
        summary: 'Read Notification',
        pathParams: ['notification_id'],
        query: [],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: true,
        devOnly: false,
        download: false,
      },
    ],
  },
  {
    name: '诊断与运维自动化',
    cases: [
      {
        method: 'GET',
        path: '/diagnosis-decision-trees',
        summary: 'Diagnosis Decision Trees',
        pathParams: [],
        query: ['page', 'pageSize', 'module', 'status'],
        body: null,
        permission: 'ops:manage 写操作',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/diagnosis-decision-trees',
        summary: 'Create Diagnosis Decision Tree',
        pathParams: [],
        query: [],
        body: 'object',
        permission: 'ops:manage 写操作',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'PUT',
        path: '/diagnosis-decision-trees/{tree_id}',
        summary: 'Update Diagnosis Decision Tree',
        pathParams: ['tree_id'],
        query: [],
        body: 'object',
        permission: 'ops:manage 写操作',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/diagnosis-kb',
        summary: 'Diagnosis Kb',
        pathParams: [],
        query: ['page', 'pageSize', 'module', 'errorCode', 'keyword'],
        body: null,
        permission: 'ops:manage 写操作',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/diagnosis-kb',
        summary: 'Create Diagnosis Kb',
        pathParams: [],
        query: [],
        body: 'object',
        permission: 'ops:manage 写操作',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/diagnosis-kb/from-diagnosis/{diagnosis_id}',
        summary: 'Diagnosis Kb From Ticket',
        pathParams: ['diagnosis_id'],
        query: [],
        body: null,
        permission: 'ops:manage 写操作',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'PUT',
        path: '/diagnosis-kb/{entry_id}',
        summary: 'Update Diagnosis Kb',
        pathParams: ['entry_id'],
        query: [],
        body: 'object',
        permission: 'ops:manage 写操作',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'DELETE',
        path: '/diagnosis-kb/{entry_id}',
        summary: 'Delete Diagnosis Kb',
        pathParams: ['entry_id'],
        query: [],
        body: null,
        permission: 'ops:manage 写操作',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/diagnostics',
        summary: 'Diagnostics',
        pathParams: [],
        query: ['page', 'pageSize'],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/diagnostics/{diagnosis_id}',
        summary: 'Diagnosis Detail',
        pathParams: ['diagnosis_id'],
        query: [],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/diagnostics/{diagnosis_id}/fix',
        summary: 'Fix Diagnosis',
        pathParams: ['diagnosis_id'],
        query: [],
        body: 'object',
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/inspection-runs/{run_id}',
        summary: 'Inspection Run',
        pathParams: ['run_id'],
        query: [],
        body: null,
        permission: 'ops:manage 写操作/导出',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/inspection-runs/{run_id}/export',
        summary: 'Inspection Export',
        pathParams: ['run_id'],
        query: 'format',
        body: null,
        permission: 'ops:manage 写操作/导出',
        mutating: false,
        devOnly: false,
        download: true,
      },
      {
        method: 'GET',
        path: '/inspection-tasks',
        summary: 'Inspection Tasks',
        pathParams: [],
        query: [],
        body: null,
        permission: 'ops:manage 写操作/导出',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/inspection-tasks',
        summary: 'Create Inspection Task',
        pathParams: [],
        query: [],
        body: 'object',
        permission: 'ops:manage 写操作/导出',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/inspection-tasks/{task_id}/run',
        summary: 'Run Inspection',
        pathParams: ['task_id'],
        query: [],
        body: 'object',
        permission: 'ops:manage 写操作/导出',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/ops-tasks',
        summary: 'List Ops Tasks',
        pathParams: [],
        query: ['status', 'taskType', 'targetType', 'page', 'pageSize'],
        body: null,
        permission: 'ops:manage 写操作',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/ops-tasks',
        summary: 'Create Ops Task',
        pathParams: [],
        query: [],
        body: 'object',
        permission: 'ops:manage 写操作',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/ops-tasks/{task_id}',
        summary: 'Ops Task Detail',
        pathParams: ['task_id'],
        query: [],
        body: null,
        permission: 'ops:manage 写操作',
        mutating: false,
        devOnly: false,
        download: false,
      },
    ],
  },
  {
    name: '成本核算',
    cases: [
      {
        method: 'GET',
        path: '/budgets',
        summary: 'List Budgets',
        pathParams: [],
        query: ['scopeType', 'scopeId', 'status', 'page', 'pageSize'],
        body: null,
        permission: 'security:manage',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/budgets',
        summary: 'Create Budget',
        pathParams: [],
        query: [],
        body: 'BudgetRequest',
        permission: 'security:manage',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'PUT',
        path: '/budgets/{budget_id}',
        summary: 'Update Budget',
        pathParams: ['budget_id'],
        query: [],
        body: 'object',
        permission: 'security:manage',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/budgets/{budget_id}/evaluate',
        summary: 'Evaluate Budget',
        pathParams: ['budget_id'],
        query: [],
        body: 'object',
        permission: 'security:manage',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/cost-rules',
        summary: 'List Cost Rules',
        pathParams: [],
        query: ['ruleType', 'status', 'page', 'pageSize'],
        body: null,
        permission: 'security:manage',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/cost-rules',
        summary: 'Create Cost Rule',
        pathParams: [],
        query: [],
        body: 'CostRuleRequest',
        permission: 'security:manage',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/cost/by-agent',
        summary: 'Cost',
        pathParams: [],
        query: [],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/cost/by-department',
        summary: 'Cost',
        pathParams: [],
        query: [],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/cost/by-model',
        summary: 'Cost',
        pathParams: [],
        query: [],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/cost/by-project',
        summary: 'Cost',
        pathParams: [],
        query: [],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/cost/by-resource-package',
        summary: 'Cost',
        pathParams: [],
        query: [],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/cost/export',
        summary: 'Cost Export',
        pathParams: [],
        query: ['dimension', 'startDate', 'endDate'],
        body: null,
        permission: 'security:manage',
        mutating: false,
        devOnly: false,
        download: true,
      },
      {
        method: 'GET',
        path: '/cost/overview',
        summary: 'Cost',
        pathParams: [],
        query: [],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/resource-packages',
        summary: 'List Resource Packages',
        pathParams: [],
        query: ['targetType', 'targetId', 'status', 'page', 'pageSize'],
        body: null,
        permission: 'security:manage',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/resource-packages',
        summary: 'Create Resource Package',
        pathParams: [],
        query: [],
        body: 'ResourcePackageRequest',
        permission: 'security:manage',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'PUT',
        path: '/resource-packages/{package_id}',
        summary: 'Update Resource Package',
        pathParams: ['package_id'],
        query: [],
        body: 'object',
        permission: 'security:manage',
        mutating: true,
        devOnly: false,
        download: false,
      },
    ],
  },
  {
    name: '审计、安全与导出',
    cases: [
      {
        method: 'GET',
        path: '/audit/export',
        summary: 'Audit Export',
        pathParams: [],
        query: 'approvalId',
        body: null,
        permission: 'audit:view / audit:export 按接口区分',
        mutating: false,
        devOnly: false,
        download: true,
      },
      {
        method: 'GET',
        path: '/audit/login-logs',
        summary: 'Audit Login Logs',
        pathParams: [],
        query: ['page', 'pageSize', 'userId', 'status', 'startTime', 'endTime'],
        body: null,
        permission: 'audit:view / audit:export 按接口区分',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/audit/operation-logs',
        summary: 'Operation Logs',
        pathParams: [],
        query: ['page', 'pageSize', 'module', 'actorId', 'action', 'startTime', 'endTime'],
        body: null,
        permission: 'audit:view / audit:export 按接口区分',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/audit/sensitive-events',
        summary: 'Sensitive Events',
        pathParams: [],
        query: ['page', 'pageSize', 'eventType', 'objectType', 'objectId', 'actorId', 'result'],
        body: null,
        permission: 'audit:view / audit:export 按接口区分',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/exports',
        summary: 'List Exports',
        pathParams: [],
        query: ['page', 'pageSize', 'type', 'status', 'applicantId'],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: false,
        devOnly: false,
        download: true,
      },
      {
        method: 'GET',
        path: '/exports/{export_key}',
        summary: 'Get Export',
        pathParams: ['export_key'],
        query: [],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: false,
        devOnly: false,
        download: true,
      },
      {
        method: 'GET',
        path: '/exports/{export_key}/download',
        summary: 'Download Export',
        pathParams: ['export_key'],
        query: [],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: false,
        devOnly: false,
        download: true,
      },
      {
        method: 'GET',
        path: '/security-policies',
        summary: 'Security Policies',
        pathParams: [],
        query: ['category', 'status'],
        body: null,
        permission: 'security:manage',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/security-policies/{policy_id}',
        summary: 'Security Policy Detail',
        pathParams: ['policy_id'],
        query: [],
        body: null,
        permission: 'security:manage',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'PUT',
        path: '/security-policies/{policy_id}',
        summary: 'Update Security Policy',
        pathParams: ['policy_id'],
        query: [],
        body: 'object',
        permission: 'security:manage',
        mutating: true,
        devOnly: false,
        download: false,
      },
    ],
  },
  {
    name: '审批、席位与共享',
    cases: [
      {
        method: 'GET',
        path: '/agents/{agent_id}/share-grants',
        summary: 'List Share',
        pathParams: ['agent_id'],
        query: [],
        body: null,
        permission: 'agent:share',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/agents/{agent_id}/share-grants',
        summary: 'Create Share',
        pathParams: ['agent_id'],
        query: [],
        body: 'object',
        permission: 'agent:share',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'DELETE',
        path: '/agents/{agent_id}/share-grants/{grant_id}',
        summary: 'Delete Share',
        pathParams: ['agent_id', 'grant_id'],
        query: [],
        body: null,
        permission: 'agent:share',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/approvals',
        summary: 'Approvals',
        pathParams: [],
        query: ['page', 'pageSize', 'status', 'type'],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/approvals',
        summary: 'Create Approval',
        pathParams: [],
        query: [],
        body: 'object',
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/approvals/{approval_id}',
        summary: 'Approval Detail',
        pathParams: ['approval_id'],
        query: [],
        body: null,
        permission: 'approval:manage 决策；创建/列表登录可用',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/approvals/{approval_id}/approve',
        summary: 'Approval Action',
        pathParams: ['approval_id'],
        query: [],
        body: 'object',
        permission: 'approval:manage 决策；创建/列表登录可用',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/approvals/{approval_id}/reject',
        summary: 'Approval Action',
        pathParams: ['approval_id'],
        query: [],
        body: 'object',
        permission: 'approval:manage 决策；创建/列表登录可用',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/seat-assignments',
        summary: 'Seat Assignments',
        pathParams: [],
        query: ['departmentId', 'userId', 'agentId'],
        body: null,
        permission: 'seat:manage',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/seat-assignments',
        summary: 'Create Seat Assignment',
        pathParams: [],
        query: [],
        body: 'object',
        permission: 'seat:manage',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'DELETE',
        path: '/seat-assignments/{assignment_id}',
        summary: 'Delete Seat Assignment',
        pathParams: ['assignment_id'],
        query: [],
        body: null,
        permission: 'seat:manage',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/seat-assignments/{assignment_id}/transfer',
        summary: 'Transfer Seat',
        pathParams: ['assignment_id'],
        query: [],
        body: 'object',
        permission: 'seat:manage',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/seat-events',
        summary: 'Seat Events',
        pathParams: [],
        query: ['page', 'pageSize', 'seatPackageId', 'assignmentId', 'eventType', 'assigneeId'],
        body: null,
        permission: 'seat:manage',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/seat-packages',
        summary: 'Seat Packages',
        pathParams: [],
        query: [],
        body: null,
        permission: 'seat:manage',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/seat-packages',
        summary: 'Create Seat Package',
        pathParams: [],
        query: [],
        body: 'object',
        permission: 'seat:manage',
        mutating: true,
        devOnly: false,
        download: false,
      },
    ],
  },
  {
    name: '渠道与业务系统',
    cases: [
      {
        method: 'GET',
        path: '/business-system-audit-logs',
        summary: 'Business System Audit Logs',
        pathParams: [],
        query: ['systemId', 'agentId', 'page', 'pageSize'],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/business-systems',
        summary: 'Business Systems',
        pathParams: [],
        query: [],
        body: null,
        permission: 'ops:manage 写操作',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/business-systems',
        summary: 'Create Business System',
        pathParams: [],
        query: [],
        body: 'object',
        permission: 'ops:manage 写操作',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/business-systems/{system_id}/access',
        summary: 'Business System Access',
        pathParams: ['system_id'],
        query: [],
        body: 'object',
        permission: 'ops:manage 写操作',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/business-systems/{system_id}/agents',
        summary: 'Business System Agents',
        pathParams: ['system_id'],
        query: [],
        body: null,
        permission: 'ops:manage 写操作',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'PUT',
        path: '/business-systems/{system_id}/agents',
        summary: 'Update Business Agents',
        pathParams: ['system_id'],
        query: [],
        body: 'object',
        permission: 'ops:manage 写操作',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/channel-audit-logs',
        summary: 'Channel Audit Logs',
        pathParams: [],
        query: ['page', 'pageSize', 'module', 'action'],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/channel-message-logs',
        summary: 'Channel Message Logs',
        pathParams: [],
        query: ['channelId', 'sourceType', 'page', 'pageSize'],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/channels',
        summary: 'Channels',
        pathParams: [],
        query: [],
        body: null,
        permission: 'ops:manage 写操作',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/channels',
        summary: 'Create Channel',
        pathParams: [],
        query: [],
        body: 'object',
        permission: 'ops:manage 写操作',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'PUT',
        path: '/channels/{channel_id}',
        summary: 'Update Channel',
        pathParams: ['channel_id'],
        query: [],
        body: 'object',
        permission: 'ops:manage 写操作',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/channels/{channel_id}/agents',
        summary: 'Channel Agents',
        pathParams: ['channel_id'],
        query: [],
        body: null,
        permission: 'ops:manage 写操作',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'PUT',
        path: '/channels/{channel_id}/agents',
        summary: 'Update Channel Agents',
        pathParams: ['channel_id'],
        query: [],
        body: 'object',
        permission: 'ops:manage 写操作',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/channels/{channel_id}/disable',
        summary: 'Channel Action',
        pathParams: ['channel_id'],
        query: [],
        body: null,
        permission: 'ops:manage 写操作',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/channels/{channel_id}/messages',
        summary: 'Create Channel Message',
        pathParams: ['channel_id'],
        query: [],
        body: 'object',
        permission: 'ops:manage 写操作',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/channels/{channel_id}/reconnect',
        summary: 'Channel Action',
        pathParams: ['channel_id'],
        query: [],
        body: null,
        permission: 'ops:manage 写操作',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/channels/{channel_id}/test',
        summary: 'Channel Action',
        pathParams: ['channel_id'],
        query: [],
        body: null,
        permission: 'ops:manage 写操作',
        mutating: true,
        devOnly: false,
        download: false,
      },
    ],
  },
  {
    name: '记忆与运行时代理',
    cases: [
      {
        method: 'POST',
        path: '/agents/{agent_id}/backup-restore',
        summary: 'Restore Backup',
        pathParams: ['agent_id'],
        query: [],
        body: 'object',
        permission: 'agent:ops 写操作',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/agents/{agent_id}/backup-restore/{task_id}',
        summary: 'Backup Status',
        pathParams: ['agent_id', 'task_id'],
        query: [],
        body: null,
        permission: 'agent:ops 写操作',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/agents/{agent_id}/backups',
        summary: 'Start Backup',
        pathParams: ['agent_id'],
        query: [],
        body: null,
        permission: 'agent:ops 写操作',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'DELETE',
        path: '/agents/{agent_id}/backups',
        summary: 'Delete Backups',
        pathParams: ['agent_id'],
        query: [],
        body: null,
        permission: 'agent:ops 写操作',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/agents/{agent_id}/backups/{task_id}',
        summary: 'Backup Status',
        pathParams: ['agent_id', 'task_id'],
        query: [],
        body: null,
        permission: 'agent:ops 写操作',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/agents/{agent_id}/crons',
        summary: 'List Crons',
        pathParams: ['agent_id'],
        query: [],
        body: null,
        permission: 'agent:ops 写操作',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/agents/{agent_id}/crons',
        summary: 'Create Cron',
        pathParams: ['agent_id'],
        query: [],
        body: 'object',
        permission: 'agent:ops 写操作',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'PUT',
        path: '/agents/{agent_id}/crons/{cron_id}',
        summary: 'Update Cron',
        pathParams: ['agent_id', 'cron_id'],
        query: [],
        body: 'object',
        permission: 'agent:ops 写操作',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'DELETE',
        path: '/agents/{agent_id}/crons/{cron_id}',
        summary: 'Delete Cron',
        pathParams: ['agent_id', 'cron_id'],
        query: [],
        body: null,
        permission: 'agent:ops 写操作',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/agents/{agent_id}/crons/{cron_id}/runs',
        summary: 'Cron Runs',
        pathParams: ['agent_id', 'cron_id'],
        query: 'limit',
        body: null,
        permission: 'agent:ops 写操作',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/agents/{agent_id}/dev-file/content',
        summary: 'Dev File Content',
        pathParams: ['agent_id'],
        query: 'path*',
        body: null,
        permission: 'agent:ops 写操作',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'PUT',
        path: '/agents/{agent_id}/dev-file/content',
        summary: 'Save Dev File',
        pathParams: ['agent_id'],
        query: [],
        body: 'object',
        permission: 'agent:ops 写操作',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/agents/{agent_id}/dev-file/download',
        summary: 'Download Dev File',
        pathParams: ['agent_id'],
        query: 'path*',
        body: null,
        permission: 'agent:view/create/deploy/delete/ops/batch/share 按动作区分',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/agents/{agent_id}/dev-file/meta',
        summary: 'Dev File Meta',
        pathParams: ['agent_id'],
        query: 'path*',
        body: null,
        permission: 'agent:view/create/deploy/delete/ops/batch/share 按动作区分',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/agents/{agent_id}/dev-files',
        summary: 'Dev Files',
        pathParams: ['agent_id'],
        query: ['path', 'page', 'pageSize'],
        body: null,
        permission: 'agent:view/create/deploy/delete/ops/batch/share 按动作区分',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/agents/{agent_id}/dev-files/search',
        summary: 'Dev File Search',
        pathParams: ['agent_id'],
        query: ['keyword*', 'path'],
        body: null,
        permission: 'agent:view/create/deploy/delete/ops/batch/share 按动作区分',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/agents/{agent_id}/memory-preview',
        summary: 'Memory Preview',
        pathParams: ['agent_id'],
        query: [],
        body: null,
        permission: 'agent:view/create/deploy/delete/ops/batch/share 按动作区分',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/agents/{agent_id}/plugins/astronmem',
        summary: 'Astronmem Status',
        pathParams: ['agent_id'],
        query: [],
        body: null,
        permission: 'agent:ops 写操作',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/agents/{agent_id}/plugins/astronmem',
        summary: 'Astronmem Toggle',
        pathParams: ['agent_id'],
        query: [],
        body: 'object',
        permission: 'agent:ops 写操作',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/agents/{agent_id}/runtime-skills',
        summary: 'Runtime Skills',
        pathParams: ['agent_id'],
        query: [],
        body: null,
        permission: 'agent:view/create/deploy/delete/ops/batch/share 按动作区分',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/agents/{agent_id}/skill-env-vars',
        summary: 'Skill Env Vars',
        pathParams: ['agent_id'],
        query: [],
        body: null,
        permission: 'agent:ops 写操作',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'PUT',
        path: '/agents/{agent_id}/skill-env-vars',
        summary: 'Put Skill Env Vars',
        pathParams: ['agent_id'],
        query: [],
        body: 'object',
        permission: 'agent:ops 写操作',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'DELETE',
        path: '/agents/{agent_id}/skill-env-vars',
        summary: 'Delete Skill Env Vars',
        pathParams: ['agent_id'],
        query: [],
        body: 'object',
        permission: 'agent:ops 写操作',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/agents/{agent_id}/teams',
        summary: 'Teams',
        pathParams: ['agent_id'],
        query: 'sessionId*',
        body: null,
        permission: 'agent:view/create/deploy/delete/ops/batch/share 按动作区分',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/agents/{agent_id}/teams/{team_id}/outputs',
        summary: 'Team Kind',
        pathParams: ['agent_id', 'team_id'],
        query: 'sessionId*',
        body: null,
        permission: 'agent:view/create/deploy/delete/ops/batch/share 按动作区分',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/agents/{agent_id}/teams/{team_id}/progress',
        summary: 'Team Kind',
        pathParams: ['agent_id', 'team_id'],
        query: 'sessionId*',
        body: null,
        permission: 'agent:view/create/deploy/delete/ops/batch/share 按动作区分',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/agents/{agent_id}/teams/{team_id}/result',
        summary: 'Team Kind',
        pathParams: ['agent_id', 'team_id'],
        query: 'sessionId*',
        body: null,
        permission: 'agent:view/create/deploy/delete/ops/batch/share 按动作区分',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/memories',
        summary: 'Memories',
        pathParams: [],
        query: [],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: false,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/memories',
        summary: 'Create Memory',
        pathParams: [],
        query: [],
        body: 'object',
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'PUT',
        path: '/memories/{memory_id}',
        summary: 'Update Memory',
        pathParams: ['memory_id'],
        query: [],
        body: 'object',
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'DELETE',
        path: '/memories/{memory_id}',
        summary: 'Delete Memory',
        pathParams: ['memory_id'],
        query: [],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'POST',
        path: '/memories/{memory_id}/share',
        summary: 'Share Memory',
        pathParams: ['memory_id'],
        query: [],
        body: 'object',
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: true,
        devOnly: false,
        download: false,
      },
      {
        method: 'GET',
        path: '/memory-share-requests',
        summary: 'Memory Share Requests',
        pathParams: [],
        query: ['status', 'memoryId', 'page', 'pageSize'],
        body: null,
        permission: '登录用户；部分写操作按 RBAC 校验',
        mutating: false,
        devOnly: false,
        download: false,
      },
    ],
  },
] satisfies ApiContractGroup[];
